CC     = gcc
CFLAGS = -Wall -Wextra

p1: p1_read.c fs_ops.c
	$(CC) $(CFLAGS) -o p1 p1_read.c fs_ops.c
p2: p2_write.c fs_ops.c
	$(CC) $(CFLAGS) -o p2 p2_write.c fs_ops.c
p3: p3_exec.c fs_ops.c
	$(CC) $(CFLAGS) -o p3 p3_exec.c fs_ops.c